services:
    _defaults:
        autoconfigure: true
        autowire: true

    # Контроллеры
    Free2er\OAuth\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Репозитории
    Free2er\OAuth\Repository\:
        resource: '../../Repository'

    # Сервисы
    Free2er\OAuth\Service\:
        resource: '../../Service'

    # Сервис клиентов
    Free2er\OAuth\Service\ClientService:
        tags: ['oauth_server.scope_provider']

    # Фабрика HTTP-сообщений Symfony
    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    # Фабрика HTTP-сообщений PSR-7
    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
