Free2er\OAuth\Entity\Client:
    type: entity
    table: oauth_client
    repositoryClass: Free2er\OAuth\Repository\ClientRepository
    id:
        id:
            type: string
            length: 255
    fields:
        secret:
            type: string
            length: 255
            options:
                default: ''
        uri:
            type: string
            length: 255
            options:
                default: ''
        grants:
            type: simple_array
            nullable: true
        scopes:
            type: simple_array
            nullable: true
        createdAt:
            type: datetime
            options:
                default: CURRENT_TIMESTAMP
        lockedAt:
            type: datetime
            nullable: true
